import React, { memo } from 'react';
import {
    Accessibility,
    AlertCircle,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    Award,
    BookOpen,
    Bot,
    Brain,
    Briefcase,
    Building,
    Calculator,
    Calendar,
    Car,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronRight,
    Chrome,
    Clock,
    Cloud,
    Cpu,
    CreditCard,
    Database,
    DollarSign,
    ExternalLink,
    Eye,
    Facebook,
    FileText,
    Film,
    FlaskConical,
    Gauge,
    GitCompare,
    Github,
    Globe,
    Heart,
    HelpCircle,
    Instagram,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    LifeBuoy,
    Lightbulb,
    LineChart,
    Linkedin,
    Lock,
    Mail,
    MapPin,
    Megaphone,
    Menu,
    MessageSquare,
    Mic,
    Minus,
    MousePointer,
    Package,
    Palette,
    Pause,
    PenSquare,
    PenTool,
    Phone,
    Play,
    PlayCircle,
    Plug,
    Plus,
    Quote,
    Receipt,
    RefreshCw,
    Repeat,
    Rocket,
    Search,
    SearchX,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Star,
    Tag,
    Target,
    TrendingDown,
    TrendingUp,
    Twitter,
    User,
    Users,
    Video,
    Workflow,
    X,
    Youtube,
    Zap,
} from 'lucide-react';

// Explicit map enables tree-shaking by avoiding `import * as Lucide` barrel.
// Add new icons here only as they are actually used.
const ICONS = {
    Accessibility,
    AlertCircle,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    Award,
    BookOpen,
    Bot,
    Brain,
    Briefcase,
    Building,
    Calculator,
    Calendar,
    Car,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronRight,
    Chrome,
    Clock,
    Cloud,
    Cpu,
    CreditCard,
    Database,
    DollarSign,
    ExternalLink,
    Eye,
    Facebook,
    FileText,
    Film,
    FlaskConical,
    Gauge,
    GitCompare,
    Github,
    Globe,
    Heart,
    HelpCircle,
    Instagram,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    LifeBuoy,
    Lightbulb,
    LineChart,
    Linkedin,
    Lock,
    Mail,
    MapPin,
    Megaphone,
    Menu,
    MessageSquare,
    Mic,
    Minus,
    MousePointer,
    Package,
    Palette,
    Pause,
    PenSquare,
    PenTool,
    Phone,
    Play,
    PlayCircle,
    Plug,
    Plus,
    Quote,
    Receipt,
    RefreshCw,
    Repeat,
    Rocket,
    Search,
    SearchX,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Star,
    Tag,
    Target,
    TrendingDown,
    TrendingUp,
    Twitter,
    User,
    Users,
    Video,
    Workflow,
    X,
    Youtube,
    Zap,
};

function Icon({
    name,
    size = 24,
    color = "currentColor",
    className = "",
    strokeWidth = 2,
    ...props
}) {
    const IconComponent = ICONS[name];

    if (!IconComponent) {
        return <HelpCircle size={size} color="gray" strokeWidth={strokeWidth} className={className} {...props} />;
    }

    return (
        <IconComponent
            size={size}
            color={color}
            strokeWidth={strokeWidth}
            className={className}
            {...props}
        />
    );
}

export default memo(Icon);
